name: about
timestamp: 1515072045
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1513089165
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-2770: 'System Messages'
  logo:
    logo-5067: 'Logo / Image'
    logo-5980: 'Logo / Image'
    logo-2980: 'Logo / Image'
  menu:
    menu-3355: Menu
    menu-9529: Menu
    menu-6699: Menu
  custom:
    custom-6122: 'Custom HTML'
    custom-3566: 'Custom HTML'
    custom-9016: 'Custom HTML'
    custom-2018: 'Custom HTML'
  contentarray:
    contentarray-7489: 'WordPress Posts'
    contentarray-9821: 'WordPress Posts'
  social:
    social-2204: Social
    social-3680: Social
  copyright:
    copyright-3946: Copyright
  spacer:
    spacer-2331: Spacer
  mobile-menu:
    mobile-menu-6875: Mobile-menu
inherit:
  default:
    footer: footer
    menu-6699: menu-3453
    logo-2980: logo-9571
    copyright-3946: copyright-1736
    spacer-2331: spacer-2556
    social-3680: social-7256
