preset: preset6
base:
  background: '#ffffff'
  text-color: '#555555'
font:
  family-default: family=Montserrat
  family-title: Montserrat
link:
  regular: '#ffffff'
  hover: '#eceeef'
navigation:
  background-image: 'gantry-media://header/pexels-photo-247298.jpeg'
  background-overlay: enabled
  text-color: '#ffffff'
header:
  background-image: 'gantry-media://header/pexels-photo-247298.jpeg'
  background-overlay: enabled
  text-color: '#ffffff'
intro:
  background: '#ffffff'
  text-color: '#555555'
features:
  background: '#660961'
utility:
  background: '#262626'
  text-color: '#ffffff'
testimonials:
  background: '#a8a7a7'
  background-image: 'gantry-media://testimonials/people-office-group-team.jpg'
  background-overlay: enabled
  text-color: '#ffffff'
footer:
  background: '#2a2a2a'
  text-color: '#cccccc'
