name: interview_request
timestamp: 1515635381
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
positions:
  breadcrumbs: Breadcrumbs
sections:
  navigation: Navigation
  header: Header
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-breadcrumbs: Breadcrumbs
  content:
    system-content-9974: 'Page Content'
  mobile-menu:
    mobile-menu-4060: Mobile-menu
  menu:
    menu-1049: Menu
    menu-1654: Menu
    menu-1601: Menu
    menu-9681: Menu
  logo:
    logo-4655: 'Logo / Image'
  copyright:
    copyright-4002: Copyright
  spacer:
    spacer-6176: Spacer
  social:
    social-2655: Social
inherit:
  blog:
    header: header
  default:
    footer: footer
    menu-1049: menu-1837
    menu-1654: menu-6570
    menu-1601: menu-9412
    menu-9681: menu-3453
    logo-4655: logo-9571
    copyright-4002: copyright-1736
    spacer-6176: spacer-2556
    social-2655: social-7256
