name: interview_request
timestamp: 1516703984
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
positions: {  }
sections:
  navigation: Navigation
  header: Header
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-5867: Breadcrumbs
    custom-3662: 'Custom HTML'
  content:
    system-content-9974: 'Page Content'
  mobile-menu:
    mobile-menu-4060: Mobile-menu
  messages:
    system-messages-7788: 'System Messages'
  logo:
    logo-5257: 'Logo / Image'
    logo-4655: 'Logo / Image'
  menu:
    menu-5331: Menu
    menu-7333: Menu
    menu-1049: Menu
    menu-1654: Menu
    menu-1601: Menu
    menu-9681: Menu
  copyright:
    copyright-4002: Copyright
  spacer:
    spacer-6176: Spacer
  social:
    social-2655: Social
inherit:
  about:
    navigation: navigation
    custom-5867: custom-3566
    system-messages-7788: system-messages-2770
    logo-5257: logo-5067
    menu-5331: menu-3355
    custom-3662: custom-6122
  default:
    footer: footer
    menu-1049: menu-1837
    menu-1654: menu-6570
    menu-1601: menu-9412
    menu-9681: menu-3453
    logo-4655: logo-9571
    copyright-4002: copyright-1736
    spacer-6176: spacer-2556
    social-2655: social-7256
