version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
layout:
  /navigation/:
    -
      - system-messages-7788
    -
      - 'logo-5257 25'
      - 'menu-2658 50'
      - 'menu-1275 25'
    -
      - custom-3662
  /header/: {  }
  /main/:
    -
      - custom-5867
    -
      - system-content-9974
  footer: {  }
  offcanvas:
    -
      - mobile-menu-4060
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
  header:
    attributes:
      boxed: '2'
      class: ''
  main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  system-messages-7788:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: system-messages-2770
  logo-5257:
    title: 'Logo / Image'
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: logo-5067
  menu-2658:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-2524
  menu-1275:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-5767
  custom-3662:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"tagline\">\n   <h1>Interview Request</h1>\n</div>"
  custom-5867:
    title: Breadcrumbs
    inherit:
      outline: about
      particle: custom-3566
      include:
        - attributes
        - block
