name: cart
timestamp: 1531484522
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
positions: {  }
sections:
  navigation: Navigation
  header: Header
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-2400: Breadcrumbs
    custom-7708: 'Custom HTML'
  content:
    system-content-9800: 'Page Content'
  mobile-menu:
    mobile-menu-1404: Mobile-menu
  messages:
    system-messages-7907: 'System Messages'
  logo:
    logo-3285: 'Logo / Image'
    logo-6532: 'Logo / Image'
  menu:
    menu-8722: Menu
    menu-1811: Menu
    menu-7879: Menu
    menu-5425: Menu
    menu-5931: Menu
    menu-4244: Menu
  copyright:
    copyright-8180: Copyright
  spacer:
    spacer-8224: Spacer
  social:
    social-8956: Social
inherit:
  about:
    navigation: navigation
    custom-2400: custom-3566
    system-messages-7907: system-messages-2770
    logo-3285: logo-5067
    menu-8722: menu-2524
    menu-1811: menu-5767
    custom-7708: custom-6122
  default:
    footer: footer
    menu-7879: menu-1837
    menu-5425: menu-6570
    menu-5931: menu-9412
    menu-4244: menu-3453
    logo-6532: logo-9571
    copyright-8180: copyright-1736
    spacer-8224: spacer-2556
    social-8956: social-7256
