version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
layout:
  /navigation/:
    -
      - system-messages-7972
    -
      - 'logo-9608 15'
      - 'menu-6409 65'
  /header/: {  }
  /main/:
    -
      - position-breadcrumbs
    -
      - system-content-8099
  /footer/:
    -
      - position-footer
    -
      - 'copyright-6470 40'
      - 'spacer-4468 30'
      - 'branding-5506 30'
  offcanvas:
    -
      - mobile-menu-1404
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
