version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
layout:
  /navigation/:
    -
      - system-messages-2972
    -
      - 'logo-9604 30'
      - 'menu-9189 70'
    -
      - custom-9206
  /header/: {  }
  /main/:
    -
      - custom-2400
    -
      - system-content-9800
  footer: {  }
  offcanvas:
    -
      - mobile-menu-1404
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  system-messages-2972:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: system-messages-2770
  logo-9604:
    title: 'Logo / Image'
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: logo-5067
  menu-9189:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-3355
  custom-9206:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"tagline\">\n   <h1>Cart</h1>\n</div>"
  custom-2400:
    title: Breadcrumbs
    inherit:
      outline: about
      particle: custom-3566
      include:
        - attributes
        - block
