name: shop
timestamp: 1515865048
version: 7
preset:
  image: 'gantry-media://images/admin/layouts/2-col-left.png'
  name: 2-col-left
  timestamp: 1513308258
positions: {  }
sections:
  navigation: Navigation
  header: Header
  sidebar: Sidebar
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-8435: 'System Messages'
  logo:
    logo-3375: 'Logo / Image'
    logo-5492: 'Logo / Image'
  menu:
    menu-6896: Menu
    menu-7376: Menu
    menu-9794: Menu
    menu-3975: Menu
    menu-2627: Menu
  custom:
    custom-8780: 'Custom HTML'
  widget:
    position-widget-8211: Widget
  content:
    system-content-2401: 'Page Content'
  copyright:
    copyright-5627: Copyright
  spacer:
    spacer-6591: Spacer
  social:
    social-4357: Social
  mobile-menu:
    mobile-menu-7655: Mobile-menu
inherit:
  about:
    navigation: navigation
    system-messages-8435: system-messages-2770
    logo-3375: logo-5067
    menu-6896: menu-3355
  default:
    footer: footer
    menu-7376: menu-1837
    menu-9794: menu-6570
    menu-3975: menu-9412
    menu-2627: menu-3453
    logo-5492: logo-9571
    copyright-5627: copyright-1736
    spacer-6591: spacer-2556
    social-4357: social-7256
