version: 2
preset:
  image: 'gantry-media://images/admin/layouts/2-col-left.png'
  name: 2-col-left
  timestamp: 1513308258
layout:
  navigation:
    -
      - system-messages-8435
    -
      - 'logo-3375 30'
      - 'menu-6896 70'
    -
      - custom-8780
  /header/: {  }
  /container-main/:
    -
      -
        'sidebar 20':
          -
            - position-widget-8211
      -
        'main 80':
          -
            - system-content-2401
  footer: {  }
  offcanvas:
    -
      - mobile-menu-7655
structure:
  navigation:
    type: section
    inherit:
      outline: about
      include:
        - attributes
  header:
    attributes:
      boxed: '0'
      class: ''
  sidebar:
    type: section
    subtype: aside
    block:
      fixed: 1
  container-main:
    attributes:
      boxed: ''
      class: shop-section
      extra: {  }
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  system-messages-8435:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: system-messages-2770
  logo-3375:
    title: 'Logo / Image'
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: logo-5067
  menu-6896:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-3355
  custom-8780:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"tagline\">\n   <div class=\"tag\">Shop</div>\n   <h1>Get RC Gear</h1>\n</div>"
  position-widget-8211:
    attributes:
      enabled: 0
      widget: '{"type":"widget","widget":"woof_widget","title":"WOOF - WooCommerce Products Filter","options":{"widget":{"title":"","additional_text_before":"","redirect":"","woof_start_filtering_btn":"0","ajax_redraw":"0"}}}'
