version: 2
preset:
  image: 'gantry-media://images/admin/layouts/2-col-left.png'
  name: 2-col-left
  timestamp: 1513308258
layout:
  /navigation/: {  }
  header: {  }
  /container-main/:
    -
      -
        'sidebar 20':
          -
            - position-widget-4212
      -
        'main 80':
          -
            - system-content-2401
  footer: {  }
  offcanvas:
    -
      - mobile-menu-7655
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    inherit:
      outline: blog
      include:
        - attributes
        - children
  sidebar:
    type: section
    subtype: aside
    block:
      fixed: 1
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  position-widget-4212:
    attributes:
      widget: '{"type":"widget","widget":"woof_widget","title":"WOOF - WooCommerce Products Filter","options":{"widget":{"title":"WooCommerce Products Filter","additional_text_before":"","redirect":"","woof_start_filtering_btn":"0","ajax_redraw":"0"}}}'
      key: widget
