name: privacy
timestamp: 1524306897
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
positions: {  }
sections:
  navigation: Navigation
  header: Header
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-4709: 'System Messages'
  logo:
    logo-5136: 'Logo / Image'
    logo-5358: 'Logo / Image'
  menu:
    menu-1376: Menu
    menu-4435: Menu
    menu-9332: Menu
    menu-3767: Menu
    menu-2221: Menu
    menu-8701: Menu
  custom:
    custom-6058: 'Custom HTML'
    custom-1452: Breadcrumbs
  content:
    system-content-8940: 'Page Content'
  mobile-menu:
    mobile-menu-2592: Mobile-menu
  copyright:
    copyright-6303: Copyright
  spacer:
    spacer-1614: Spacer
  social:
    social-9870: Social
inherit:
  about:
    system-messages-4709: system-messages-2770
    logo-5136: logo-5067
    menu-1376: menu-2524
    menu-4435: menu-5767
    custom-1452: custom-3566
  default:
    footer: footer
    menu-9332: menu-1837
    menu-3767: menu-6570
    menu-2221: menu-9412
    menu-8701: menu-3453
    logo-5358: logo-9571
    copyright-6303: copyright-1736
    spacer-1614: spacer-2556
    social-9870: social-7256
