name: privacy
timestamp: 1515635381
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
positions:
  breadcrumbs: Breadcrumbs
sections:
  navigation: Navigation
  header: Header
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-breadcrumbs: Breadcrumbs
  content:
    system-content-8940: 'Page Content'
  mobile-menu:
    mobile-menu-2592: Mobile-menu
  menu:
    menu-9332: Menu
    menu-3767: Menu
    menu-2221: Menu
    menu-8701: Menu
  logo:
    logo-5358: 'Logo / Image'
  copyright:
    copyright-6303: Copyright
  spacer:
    spacer-1614: Spacer
  social:
    social-9870: Social
inherit:
  blog:
    header: header
  default:
    footer: footer
    menu-9332: menu-1837
    menu-3767: menu-6570
    menu-2221: menu-9412
    menu-8701: menu-3453
    logo-5358: logo-9571
    copyright-6303: copyright-1736
    spacer-1614: spacer-2556
    social-9870: social-7256
