version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
layout:
  /navigation/: {  }
  header: {  }
  /main/:
    -
      - position-breadcrumbs
    -
      - system-content-8940
  footer: {  }
  offcanvas:
    -
      - mobile-menu-2592
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    inherit:
      outline: blog
      include:
        - attributes
        - children
  main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - children
        - attributes
content:
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
