version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
layout:
  /navigation/:
    -
      - system-messages-4709
    -
      - 'logo-5136 25'
      - 'menu-1376 50'
      - 'menu-4435 25'
    -
      - custom-6058
  /header/: {  }
  /main/:
    -
      - custom-1452
    -
      - system-content-8940
  footer: {  }
  offcanvas:
    -
      - mobile-menu-2592
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
  header:
    attributes:
      boxed: '2'
      class: ''
  main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - children
        - attributes
content:
  system-messages-4709:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: system-messages-2770
  logo-5136:
    title: 'Logo / Image'
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: logo-5067
  menu-1376:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-2524
  menu-4435:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-5767
  custom-6058:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"tagline\">\n   <h1>Privacy</h1>\n</div>"
  custom-1452:
    title: Breadcrumbs
    inherit:
      outline: about
      particle: custom-3566
      include:
        - attributes
        - block
