name: terms_and_conditions
timestamp: 1530089459
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
positions: {  }
sections:
  navigation: Navigation
  header: Header
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-3528: 'System Messages'
  logo:
    logo-1805: 'Logo / Image'
    logo-4808: 'Logo / Image'
  menu:
    menu-6869: Menu
    menu-6279: Menu
    menu-2551: Menu
    menu-9659: Menu
    menu-5954: Menu
    menu-4466: Menu
  custom:
    custom-7510: 'Custom HTML'
    custom-5403: Breadcrumbs
  content:
    system-content-9689: 'Page Content'
  mobile-menu:
    mobile-menu-8828: Mobile-menu
  copyright:
    copyright-8679: Copyright
  spacer:
    spacer-2311: Spacer
  social:
    social-1146: Social
inherit:
  about:
    system-messages-3528: system-messages-2770
    logo-1805: logo-5067
    menu-6869: menu-2524
    menu-6279: menu-5767
    custom-5403: custom-3566
  default:
    footer: footer
    menu-2551: menu-1837
    menu-9659: menu-6570
    menu-5954: menu-9412
    menu-4466: menu-3453
    logo-4808: logo-9571
    copyright-8679: copyright-1736
    spacer-2311: spacer-2556
    social-1146: social-7256
