name: terms_and_conditions
timestamp: 1516703984
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
positions: {  }
sections:
  navigation: Navigation
  header: Header
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-5403: Breadcrumbs
  content:
    system-content-9689: 'Page Content'
  mobile-menu:
    mobile-menu-8828: Mobile-menu
  menu:
    menu-2551: Menu
    menu-9659: Menu
    menu-5954: Menu
    menu-4466: Menu
  logo:
    logo-4808: 'Logo / Image'
  copyright:
    copyright-8679: Copyright
  spacer:
    spacer-2311: Spacer
  social:
    social-1146: Social
inherit:
  blog:
    header: header
  about:
    custom-5403: custom-3566
  default:
    footer: footer
    menu-2551: menu-1837
    menu-9659: menu-6570
    menu-5954: menu-9412
    menu-4466: menu-3453
    logo-4808: logo-9571
    copyright-8679: copyright-1736
    spacer-2311: spacer-2556
    social-1146: social-7256
