name: rc_of_the_month
timestamp: 1516703984
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
positions:
  footer: Footer
sections:
  navigation: Navigation
  header: Header
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-7972: 'System Messages'
  logo:
    logo-9608: Logo
  menu:
    menu-6409: Menu
  custom:
    custom-6034: Breadcrumbs
  content:
    system-content-7703: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-5001: Copyright
  spacer:
    spacer-9293: Spacer
  branding:
    branding-2142: Branding
  mobile-menu:
    mobile-menu-6314: Mobile-menu
inherit:
  about:
    custom-6034: custom-3566
