version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
layout:
  /navigation/:
    -
      - system-messages-3964
    -
      - 'logo-1152 25'
      - 'menu-6886 50'
      - 'menu-3365 25'
    -
      - custom-2105
  /header/: {  }
  /main/:
    -
      - custom-6034
    -
      - contentarray-2909
  /footer/:
    -
      - position-footer
    -
      - 'copyright-5001 40'
      - 'spacer-9293 30'
      - 'branding-2142 30'
  offcanvas:
    -
      - mobile-menu-6314
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  system-messages-3964:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: system-messages-2770
  logo-1152:
    title: 'Logo / Image'
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: logo-5067
  menu-6886:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-2524
  menu-3365:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-5767
  custom-2105:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"tagline\">\n   <h1>RC of the Month</h1>\n</div>"
  custom-6034:
    title: Breadcrumbs
    inherit:
      outline: about
      particle: custom-3566
      include:
        - attributes
        - block
  contentarray-2909:
    title: 'WordPress Posts'
    attributes:
      post:
        filter:
          categories: '83'
          posts: ''
          sticky: ''
        limit:
          total: ''
          columns: '1'
          start: '0'
        sort:
          orderby: date
          ordering: ASC
        display:
          title:
            enabled: show
          read_more:
            enabled: ''
          category:
            enabled: show
          text:
            type: content
            limit: '100'
            formatting: html
      css:
        class: ''
    block:
      id: rc-of-the-month
  position-footer:
    attributes:
      key: footer
