version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
layout:
  /navigation/:
    -
      - system-messages-7972
    -
      - 'logo-9608 19'
      - 'menu-6409 81'
  /header/: {  }
  /main/:
    -
      - custom-6034
    -
      - system-content-7703
  /footer/:
    -
      - position-footer
    -
      - 'copyright-5001 40'
      - 'spacer-9293 30'
      - 'branding-2142 30'
  offcanvas:
    -
      - mobile-menu-6314
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  custom-6034:
    title: Breadcrumbs
    inherit:
      outline: about
      particle: custom-3566
      include:
        - attributes
        - block
  position-footer:
    attributes:
      key: footer
