version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
layout:
  /navigation/:
    -
      - system-messages-7375
    -
      - 'logo-3294 25'
      - 'menu-4311 50'
      - 'menu-1634 25'
    -
      - custom-5133
  /header/: {  }
  /main/:
    -
      - custom-6296
    -
      - system-content-9283
  footer: {  }
  offcanvas:
    -
      - mobile-menu-7513
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
      class: account-section
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  system-messages-7375:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: system-messages-2770
  logo-3294:
    title: 'Logo / Image'
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: logo-5067
  menu-4311:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-2524
  menu-1634:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-5767
  custom-5133:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"tagline\">\n   <h1>Account</h1>\n</div>"
  custom-6296:
    title: Breadcrumbs
    inherit:
      outline: about
      particle: custom-3566
      include:
        - attributes
        - block
  system-content-9283:
    block:
      class: 'menu menu-vertical'
