name: shipping_information
timestamp: 1513607691
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
positions:
  breadcrumbs: Breadcrumbs
sections:
  navigation: Navigation
  header: Header
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-2674: 'Logo / Image'
    logo-7540: 'Logo / Image'
  menu:
    menu-8864: Menu
    menu-8949: Menu
  messages:
    system-messages-2420: 'System Messages'
  position:
    position-breadcrumbs: Breadcrumbs
  content:
    system-content-3083: 'Page Content'
  copyright:
    copyright-2099: Copyright
  spacer:
    spacer-7460: Spacer
  social:
    social-9069: Social
  mobile-menu:
    mobile-menu-8672: Mobile-menu
inherit:
  blog:
    header: header
    logo-2674: logo-4799
    menu-8864: menu-6098
    system-messages-2420: system-messages-3860
  default:
    footer: footer
    menu-8949: menu-3453
    logo-7540: logo-9571
    copyright-2099: copyright-1736
    spacer-7460: spacer-2556
    social-9069: social-7256
