name: shipping_information
timestamp: 1516703984
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
positions: {  }
sections:
  navigation: Navigation
  header: Header
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-7029: Breadcrumbs
  content:
    system-content-3083: 'Page Content'
  mobile-menu:
    mobile-menu-8672: Mobile-menu
  menu:
    menu-2992: Menu
    menu-1998: Menu
    menu-3193: Menu
    menu-8949: Menu
  logo:
    logo-7540: 'Logo / Image'
  copyright:
    copyright-2099: Copyright
  spacer:
    spacer-7460: Spacer
  social:
    social-9069: Social
inherit:
  blog:
    header: header
  about:
    custom-7029: custom-3566
  default:
    footer: footer
    menu-2992: menu-1837
    menu-1998: menu-6570
    menu-3193: menu-9412
    menu-8949: menu-3453
    logo-7540: logo-9571
    copyright-2099: copyright-1736
    spacer-7460: spacer-2556
    social-9069: social-7256
