version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
layout:
  /navigation/:
    -
      - system-messages-3558
    -
      - 'logo-8140 25'
      - 'menu-8110 50'
      - 'menu-6140 25'
    -
      - custom-5503
  /header/: {  }
  /main/:
    -
      - custom-7029
    -
      - system-content-3083
  footer: {  }
  offcanvas:
    -
      - mobile-menu-8672
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
  header:
    attributes:
      boxed: '2'
      class: ''
  main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  system-messages-3558:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: system-messages-2770
  logo-8140:
    title: 'Logo / Image'
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: logo-5067
  menu-8110:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-2524
  menu-6140:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-5767
  custom-5503:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"tagline\">\n   <h1>Shipping Information</h1>\n</div>"
  custom-7029:
    title: Breadcrumbs
    inherit:
      outline: about
      particle: custom-3566
      include:
        - attributes
        - block
