name: contact
timestamp: 1513308054
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
positions:
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  navigation: Navigation
  header: Header
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-7972: 'System Messages'
  logo:
    logo-9608: Logo
  menu:
    menu-6409: Menu
  position:
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  content:
    system-content-3503: 'Page Content'
  copyright:
    copyright-6373: Copyright
  spacer:
    spacer-4965: Spacer
  branding:
    branding-6158: Branding
  mobile-menu:
    mobile-menu-6894: Mobile-menu
inherit: {  }
