name: contact
timestamp: 1513607242
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
positions:
  breadcrumbs: Breadcrumbs
sections:
  navigation: Navigation
  header: Header
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-8835: 'Logo / Image'
    logo-4694: 'Logo / Image'
  menu:
    menu-3939: Menu
    menu-9426: Menu
  messages:
    system-messages-6219: 'System Messages'
  position:
    position-breadcrumbs: Breadcrumbs
  content:
    system-content-3388: 'Page Content'
  copyright:
    copyright-2935: Copyright
  spacer:
    spacer-1754: Spacer
  social:
    social-1046: Social
  mobile-menu:
    mobile-menu-6894: Mobile-menu
inherit:
  blog:
    header: header
    logo-8835: logo-4799
    menu-3939: menu-6098
    system-messages-6219: system-messages-3860
  default:
    footer: footer
    menu-9426: menu-3453
    logo-4694: logo-9571
    copyright-2935: copyright-1736
    spacer-1754: spacer-2556
    social-1046: social-7256
