name: contact
timestamp: 1516703984
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
positions: {  }
sections:
  navigation: Navigation
  header: Header
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-2493: Breadcrumbs
    custom-3048: 'Custom HTML'
  content:
    system-content-3388: 'Page Content'
  mobile-menu:
    mobile-menu-6894: Mobile-menu
  messages:
    system-messages-3748: 'System Messages'
  logo:
    logo-1465: 'Logo / Image'
    logo-4694: 'Logo / Image'
  menu:
    menu-6127: Menu
    menu-9885: Menu
    menu-9275: Menu
    menu-2128: Menu
    menu-9777: Menu
    menu-9426: Menu
  copyright:
    copyright-2935: Copyright
  spacer:
    spacer-1754: Spacer
  social:
    social-1046: Social
inherit:
  about:
    navigation: navigation
    custom-2493: custom-3566
    system-messages-3748: system-messages-2770
    logo-1465: logo-5067
    menu-6127: menu-3355
    custom-3048: custom-6122
  default:
    footer: footer
    menu-9275: menu-1837
    menu-2128: menu-6570
    menu-9777: menu-9412
    menu-9426: menu-3453
    logo-4694: logo-9571
    copyright-2935: copyright-1736
    spacer-1754: spacer-2556
    social-1046: social-7256
