name: contact
timestamp: 1515635381
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
positions:
  breadcrumbs: Breadcrumbs
sections:
  navigation: Navigation
  header: Header
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-breadcrumbs: Breadcrumbs
  content:
    system-content-3388: 'Page Content'
  mobile-menu:
    mobile-menu-6894: Mobile-menu
  menu:
    menu-9275: Menu
    menu-2128: Menu
    menu-9777: Menu
    menu-9426: Menu
  logo:
    logo-4694: 'Logo / Image'
  copyright:
    copyright-2935: Copyright
  spacer:
    spacer-1754: Spacer
  social:
    social-1046: Social
inherit:
  blog:
    header: header
  default:
    footer: footer
    menu-9275: menu-1837
    menu-2128: menu-6570
    menu-9777: menu-9412
    menu-9426: menu-3453
    logo-4694: logo-9571
    copyright-2935: copyright-1736
    spacer-1754: spacer-2556
    social-1046: social-7256
