version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
layout:
  /navigation/:
    -
      - system-messages-3748
    -
      - 'logo-1465 25'
      - 'menu-5925 50'
      - 'menu-1244 25'
    -
      - custom-3048
  /header/: {  }
  /main/:
    -
      - custom-2493
    -
      - system-content-3388
  footer: {  }
  offcanvas:
    -
      - mobile-menu-6894
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
  header:
    attributes:
      boxed: '2'
      class: ''
  main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  system-messages-3748:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: system-messages-2770
  logo-1465:
    title: 'Logo / Image'
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: logo-5067
  menu-5925:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-2524
  menu-1244:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-5767
  custom-3048:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"tagline\">\n   <h1>Contact Us</h1>\n</div>"
  custom-2493:
    title: Breadcrumbs
    inherit:
      outline: about
      particle: custom-3566
      include:
        - attributes
        - block
