name: volunteer_request
timestamp: 1524306897
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
positions: {  }
sections:
  navigation: Navigation
  header: Header
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-7939: 'System Messages'
  logo:
    logo-5033: 'Logo / Image'
    logo-8764: 'Logo / Image'
  menu:
    menu-9215: Menu
    menu-8797: Menu
    menu-3991: Menu
    menu-2958: Menu
    menu-5854: Menu
    menu-6578: Menu
  custom:
    custom-1495: 'Custom HTML'
    custom-8931: Breadcrumbs
  content:
    system-content-3737: 'Page Content'
  mobile-menu:
    mobile-menu-8826: Mobile-menu
  copyright:
    copyright-2700: Copyright
  spacer:
    spacer-2702: Spacer
  social:
    social-3056: Social
inherit:
  about:
    system-messages-7939: system-messages-2770
    logo-5033: logo-5067
    menu-9215: menu-2524
    menu-8797: menu-5767
    custom-8931: custom-3566
  default:
    footer: footer
    menu-3991: menu-1837
    menu-2958: menu-6570
    menu-5854: menu-9412
    menu-6578: menu-3453
    logo-8764: logo-9571
    copyright-2700: copyright-1736
    spacer-2702: spacer-2556
    social-3056: social-7256
