version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
layout:
  /navigation/:
    -
      - system-messages-7939
    -
      - 'logo-5033 25'
      - 'menu-9215 50'
      - 'menu-8797 25'
    -
      - custom-1495
  /header/: {  }
  /main/:
    -
      - custom-8931
    -
      - system-content-3737
  footer: {  }
  offcanvas:
    -
      - mobile-menu-8826
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
  header:
    attributes:
      boxed: '2'
      class: ''
  main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  system-messages-7939:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: system-messages-2770
  logo-5033:
    title: 'Logo / Image'
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: logo-5067
  menu-9215:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-2524
  menu-8797:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-5767
  custom-1495:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"tagline\">\n   <h1>Volunteer Request</h1>\n</div>"
  custom-8931:
    title: Breadcrumbs
    inherit:
      outline: about
      particle: custom-3566
      include:
        - attributes
        - block
