name: return_information
timestamp: 1515635381
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
positions:
  breadcrumbs: Breadcrumbs
sections:
  navigation: Navigation
  header: Header
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-breadcrumbs: Breadcrumbs
  content:
    system-content-6865: 'Page Content'
  mobile-menu:
    mobile-menu-8677: Mobile-menu
  menu:
    menu-3096: Menu
    menu-8595: Menu
    menu-5431: Menu
    menu-4147: Menu
  logo:
    logo-6529: 'Logo / Image'
  copyright:
    copyright-3810: Copyright
  spacer:
    spacer-8867: Spacer
  social:
    social-9813: Social
inherit:
  blog:
    header: header
  default:
    footer: footer
    menu-3096: menu-1837
    menu-8595: menu-6570
    menu-5431: menu-9412
    menu-4147: menu-3453
    logo-6529: logo-9571
    copyright-3810: copyright-1736
    spacer-8867: spacer-2556
    social-9813: social-7256
