version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
layout:
  /navigation/: {  }
  header: {  }
  /main/:
    -
      - custom-5088
    -
      - system-content-6865
  footer: {  }
  offcanvas:
    -
      - mobile-menu-8677
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    inherit:
      outline: blog
      include:
        - attributes
        - children
  main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  custom-5088:
    title: Breadcrumbs
    inherit:
      outline: about
      particle: custom-3566
      include:
        - attributes
        - block
