version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
layout:
  /navigation/:
    -
      - system-messages-6271
    -
      - 'logo-2396 25'
      - 'menu-6789 50'
      - 'menu-9892 25'
    -
      - custom-2897
  /header/: {  }
  /main/:
    -
      - custom-5088
    -
      - system-content-6865
  footer: {  }
  offcanvas:
    -
      - mobile-menu-8677
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
  header:
    attributes:
      boxed: '2'
      class: ''
  main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  system-messages-6271:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: system-messages-2770
  logo-2396:
    title: 'Logo / Image'
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: logo-5067
  menu-6789:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-2524
  menu-9892:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-5767
  custom-2897:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"tagline\">\n   <h1>Return Policy</h1>\n</div>"
  custom-5088:
    title: Breadcrumbs
    inherit:
      outline: about
      particle: custom-3566
      include:
        - attributes
        - block
