name: podcasts
timestamp: 1513429960
version: 7
preset:
  image: 'gantry-media://images/admin/layouts/2-col-right.png'
  name: 2-col-right
  timestamp: 1513307866
positions: {  }
sections:
  navigation: Navigation
  header: Header
  main: Main
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-5428: 'Logo / Image'
  menu:
    menu-1936: Menu
  messages:
    system-messages-4663: 'System Messages'
  contentarray:
    contentarray-9389: 'WordPress Posts'
    contentarray-2066: 'WordPress Posts'
  copyright:
    copyright-4707: Copyright
  spacer:
    spacer-8337: Spacer
  branding:
    branding-3391: Branding
  mobile-menu:
    mobile-menu-6798: Mobile-menu
inherit:
  blog:
    header: header
    logo-5428: logo-4799
    menu-1936: menu-6098
    system-messages-4663: system-messages-3860
    main: main
    contentarray-9389: contentarray-4262
    sidebar: sidebar
    contentarray-2066: contentarray-5790
