name: podcasts
timestamp: 1514028851
version: 7
preset:
  image: 'gantry-media://images/admin/layouts/2-col-right.png'
  name: 2-col-right
  timestamp: 1513307866
positions: {  }
sections:
  navigation: Navigation
  header: Header
  main: Main
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-5544: 'Logo / Image'
  menu:
    menu-7413: Menu
  messages:
    system-messages-3503: 'System Messages'
  content:
    system-content-1440: 'Page Content'
  copyright:
    copyright-4707: Copyright
  spacer:
    spacer-8337: Spacer
  branding:
    branding-3391: Branding
  mobile-menu:
    mobile-menu-6798: Mobile-menu
inherit: {  }
