version: 2
preset:
  image: 'gantry-media://images/admin/layouts/2-col-right.png'
  name: 2-col-right
  timestamp: 1513307866
layout:
  navigation: {  }
  /header/: {  }
  /container-main/:
    -
      -
        'main 80':
          -
            - custom-9710
          -
            - system-content-1440
          -
            - custom-5085
      -
        'sidebar 20': {  }
  footer: {  }
  offcanvas:
    -
      - mobile-menu-6798
structure:
  navigation:
    type: section
    inherit:
      outline: about
      include:
        - attributes
        - children
  header:
    attributes:
      boxed: ''
      class: ''
  main:
    attributes:
      class: ''
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
      class: podcast-section
      extra: {  }
  footer:
    inherit:
      outline: about
      include:
        - attributes
        - children
content:
  custom-9710:
    title: Breadcrumbs
    inherit:
      outline: about
      particle: custom-3566
      include:
        - attributes
        - block
  custom-5085:
    title: 'Custom HTML'
    attributes:
      html: '[grid_plus name="podcast_grid"]'
      filter: '1'
