version: 2
preset:
  image: 'gantry-media://images/admin/layouts/2-col-right.png'
  name: 2-col-right
  timestamp: 1513307866
layout:
  /navigation/: {  }
  /header/:
    -
      - 'logo-5544 25'
      - 'menu-7413 75'
    -
      - system-messages-3503
  /container-main/:
    -
      -
        'main 80':
          -
            - system-content-1440
      -
        'sidebar 20': {  }
  /footer/:
    -
      - 'copyright-4707 40'
      - 'spacer-8337 30'
      - 'branding-3391 30'
  offcanvas:
    -
      - mobile-menu-6798
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    attributes:
      boxed: ''
      class: ''
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  logo-5544:
    title: 'Logo / Image'
    attributes:
      url: ''
      target: _self
      image: 'gantry-media://2017/12/rc_logo.png'
      link: '1'
      svg: ''
      text: ''
      class: ''
  menu-7413:
    attributes:
      menu: mainmenu
      base: /
      hoverExpand: '1'
      mobileTarget: '0'
