version: 2
preset:
  image: 'gantry-media://images/admin/layouts/2-col-right.png'
  name: 2-col-right
  timestamp: 1513307866
layout:
  /navigation/: {  }
  header: {  }
  /container-main/:
    -
      -
        'main 80': {  }
      -
        'sidebar 20': {  }
  /footer/:
    -
      - 'copyright-4707 40'
      - 'spacer-8337 30'
      - 'branding-3391 30'
  offcanvas:
    -
      - mobile-menu-6798
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    inherit:
      outline: blog
      include:
        - attributes
        - children
  main:
    inherit:
      outline: blog
      include:
        - attributes
        - block
        - children
  sidebar:
    type: section
    subtype: aside
    inherit:
      outline: blog
      include:
        - attributes
        - block
        - children
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
