version: 2
preset:
  image: 'gantry-media://images/admin/layouts/2-col-right.png'
  name: 2-col-right
  timestamp: 1513307866
layout:
  /navigation/:
    -
      - system-messages-2222
    -
      - 'logo-6127 30'
      - 'menu-7613 70'
    -
      - custom-9174
  /header/: {  }
  /container-main/:
    -
      -
        'main 80':
          -
            - system-content-1440
      -
        'sidebar 20': {  }
  footer: {  }
  offcanvas:
    -
      - mobile-menu-6798
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
  header:
    attributes:
      boxed: ''
      class: ''
  main:
    attributes:
      class: podcast-section
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: about
      include:
        - attributes
        - children
content:
  system-messages-2222:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: system-messages-2770
  logo-6127:
    title: 'Logo / Image'
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: logo-5067
  menu-7613:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-3355
  custom-9174:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"tagline\">\n   <div class=\"tag\">Podcast</div>\n   <h1>Listen Now</h1>\n</div>"
