name: initiatives
timestamp: 1514030717
version: 7
preset:
  image: 'gantry-media://images/admin/layouts/2-col-left.png'
  name: 2-col-left
  timestamp: 1513307855
positions:
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  navigation: Navigation
  header: Header
  sidebar: Sidebar
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-1079: 'Logo / Image'
  menu:
    menu-6997: Menu
    menu-4581: Menu
  messages:
    system-messages-2509: 'System Messages'
  position:
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  content:
    system-content-4937: 'Page Content'
  widget:
    position-widget-7034: Widget
  social:
    social-3179: Social
  copyright:
    copyright-6344: Copyright
  spacer:
    spacer-1184: Spacer
  branding:
    branding-9291: Branding
  mobile-menu:
    mobile-menu-5769: Mobile-menu
inherit:
  blog:
    navigation: navigation
    header: header
    logo-1079: logo-4799
    menu-6997: menu-6098
    system-messages-2509: system-messages-3860
