name: initiatives
timestamp: 1516703984
version: 7
preset:
  image: 'gantry-media://images/admin/layouts/2-col-left.png'
  name: 2-col-left
  timestamp: 1513307855
positions:
  footer: Footer
sections:
  navigation: Navigation
  header: Header
  sidebar: Sidebar
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  menu:
    menu-4581: Menu
    menu-7848: Menu
  custom:
    custom-8152: Breadcrumbs
    custom-4848: 'Custom HTML'
  content:
    system-content-4937: 'Page Content'
  widget:
    position-widget-7034: Widget
  social:
    social-3179: Social
  position:
    position-footer: Footer
  copyright:
    copyright-6344: Copyright
  spacer:
    spacer-1184: Spacer
  branding:
    branding-9291: Branding
  mobile-menu:
    mobile-menu-5769: Mobile-menu
  messages:
    system-messages-4129: 'System Messages'
  logo:
    logo-4941: 'Logo / Image'
inherit:
  blog:
    navigation: navigation
    header: header
    system-messages-4129: system-messages-3064
    logo-4941: logo-7607
    menu-7848: menu-1609
    custom-4848: custom-6564
  about:
    custom-8152: custom-3566
