version: 2
preset:
  image: 'gantry-media://images/admin/layouts/2-col-left.png'
  name: 2-col-left
  timestamp: 1513307855
layout:
  /navigation/:
    -
      - system-messages-7972
    -
      - 'logo-9608 15'
      - 'menu-6409 65'
  /header/: {  }
  /container-main/:
    -
      -
        'sidebar 20':
          -
            - social-7182
          -
            - position-sidebar
          -
            - position-right
      -
        'main 60':
          -
            - position-breadcrumbs
          -
            - system-messages-9361
          -
            - system-content-4937
  /footer/:
    -
      - position-footer
    -
      - 'copyright-6344 40'
      - 'spacer-1184 30'
      - 'branding-9291 30'
  offcanvas:
    -
      - mobile-menu-5769
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    attributes:
      boxed: ''
  sidebar:
    subtype: aside
    type: section
    block:
      fixed: 1
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-sidebar:
    attributes:
      key: sidebar
  position-right:
    attributes:
      key: right
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
