version: 2
preset:
  image: 'gantry-media://images/admin/layouts/2-col-left.png'
  name: 2-col-left
  timestamp: 1513307855
layout:
  navigation: {  }
  header: {  }
  /container-main/:
    -
      -
        'sidebar 20':
          -
            - menu-4581
      -
        'main 80':
          -
            - custom-8152
          -
            - system-content-4937
          -
            - 'position-widget-7034 75'
            - 'social-3179 25'
  footer: {  }
  offcanvas:
    -
      - mobile-menu-5769
structure:
  navigation:
    type: section
    inherit:
      outline: blog
      include:
        - attributes
        - children
  header:
    inherit:
      outline: blog
      include:
        - attributes
        - children
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: initiatives-section
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  menu-4581:
    attributes:
      menu: initiatives
    block:
      class: 'menu menu-vertical'
  custom-8152:
    title: Breadcrumbs
    inherit:
      outline: about
      particle: custom-3566
      include:
        - attributes
        - block
  position-widget-7034:
    attributes:
      widget: '{"type":"widget","widget":"tag_cloud","title":"Tag Cloud","options":{"widget":{"title":"","count":0,"taxonomy":"post_tag"}}}'
      key: widget
