version: 2
preset:
  image: 'gantry-media://images/admin/layouts/2-col-left.png'
  name: 2-col-left
  timestamp: 1513307855
layout:
  navigation: {  }
  header: {  }
  /container-main/:
    -
      -
        'sidebar 20':
          -
            - menu-4581
      -
        'main 80':
          -
            - position-breadcrumbs
          -
            - system-content-4937
          -
            - 'position-widget-7034 75'
            - 'social-3179 25'
  /footer/:
    -
      - position-footer
    -
      - 'copyright-6344 40'
      - 'spacer-1184 30'
      - 'branding-9291 30'
  offcanvas:
    -
      - mobile-menu-5769
structure:
  navigation:
    type: section
    inherit:
      outline: blog
      include:
        - attributes
        - children
  header:
    inherit:
      outline: blog
      include:
        - attributes
        - children
  sidebar:
    type: section
    subtype: aside
    block:
      fixed: 1
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  menu-4581:
    attributes:
      menu: initiatives
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-widget-7034:
    attributes:
      widget: '{"type":"widget","widget":"tag_cloud","title":"Tag Cloud","options":{"widget":{"title":"","count":0,"taxonomy":"post_tag"}}}'
  position-footer:
    attributes:
      key: footer
