name: home
timestamp: 1524306897
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1513089165
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-5537: 'System Messages'
  logo:
    logo-1176: 'Logo / Image'
    logo-5561: 'Logo / Image'
  menu:
    menu-8447: Menu
    menu-2768: Menu
    menu-9072: Menu
    menu-3371: Menu
    menu-2194: Menu
    menu-2197: Menu
  custom:
    custom-4448: 'Custom HTML'
    custom-6676: 'Custom HTML'
    custom-4035: 'Custom HTML'
    custom-9319: 'Custom HTML'
  owlcarousel:
    owlcarousel-4121: 'Owl Carousel'
  copyright:
    copyright-2568: Copyright
  spacer:
    spacer-4165: Spacer
  social:
    social-8906: Social
  mobile-menu:
    mobile-menu-5724: Mobile-menu
inherit:
  about:
    system-messages-5537: system-messages-2770
    logo-1176: logo-5067
    menu-8447: menu-2524
    menu-2768: menu-5767
    footer: footer
    menu-9072: menu-6699
    menu-3371: menu-3490
    menu-2194: menu-8016
    menu-2197: menu-8981
    logo-5561: logo-2980
    copyright-2568: copyright-3946
    spacer-4165: spacer-2331
    social-8906: social-3680
  default:
    offcanvas: offcanvas
    mobile-menu-5724: mobile-menu-5697
