version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1513089165
layout:
  /navigation/:
    -
      - system-messages-2784
    -
      - owlcarousel-4206
    -
      - 'logo-1433 25'
      - 'menu-1081 75'
    -
      - custom-2768
  /header/: {  }
  /intro/: {  }
  /features/: {  }
  /utility/: {  }
  /above/: {  }
  /testimonials/: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'mainbar 75':
          -
            - system-content-1451
      -
        'sidebar 25': {  }
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
  header:
    attributes:
      boxed: '2'
      class: ''
  intro:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: about
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  system-messages-2784:
    inherit:
      outline: about
      particle: system-messages-2770
      include:
        - attributes
        - block
  owlcarousel-4206:
    title: 'Owl Carousel'
    attributes:
      dots: enable
      autoplay: enable
      autoplaySpeed: ''
      imageOverlay: enable
      items:
        -
          image: 'gantry-media://header/pexels-photo-235509.jpeg'
          title: 'Shop Women'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at rutrum orci, vitae gravida purus. Duis id enim nunc. Pellentesque justo quam, posuere eu sagittis quis, varius nec risus. Mauris ante lacus, fermentum ac urna nec, bibendum ornare lorem. Mauris a metus dictum lacus accumsan imperdiet non cursus velit. '
          link: shop
          linktext: 'Shop Now'
          buttonclass: button-outline
          name: 'Shop Women'
        -
          image: 'gantry-media://header/pexels-photo-247298.jpeg'
          title: Podcasts
          desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at rutrum orci, vitae gravida purus. Duis id enim nunc. Pellentesque justo quam, posuere eu sagittis quis, varius nec risus. Mauris ante lacus, fermentum ac urna nec, bibendum ornare lorem. Mauris a metus dictum lacus accumsan imperdiet non cursus velit. '
          link: podcasts
          linktext: 'Listen Now'
          buttonclass: button-outline
          name: Podcasts
  logo-1433:
    title: 'Logo / Image'
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: logo-5067
  menu-1081:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-3355
  custom-2768:
    title: 'Custom HTML'
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: custom-6122
