version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1513089165
layout:
  /navigation/:
    -
      - system-messages-5537
    -
      - 'logo-1176 25'
      - 'menu-8447 50'
      - 'menu-2768 25'
  /header/:
    -
      - custom-4448
    -
      - owlcarousel-4121
  /intro/: {  }
  /features/: {  }
  /utility/: {  }
  /above/: {  }
  /testimonials/: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'mainbar 95':
          -
            - custom-6676
          -
            - custom-4035
          -
            - custom-9319
      -
        'sidebar 5': {  }
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
  header:
    attributes:
      boxed: '2'
      class: ''
  intro:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
    attributes:
      class: ''
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
      class: home-section
      extra: {  }
  footer:
    inherit:
      outline: about
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  system-messages-5537:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: system-messages-2770
  logo-1176:
    title: 'Logo / Image'
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: logo-5067
  menu-8447:
    inherit:
      outline: about
      particle: menu-2524
      include:
        - attributes
        - block
  menu-2768:
    inherit:
      outline: about
      particle: menu-5767
      include:
        - attributes
        - block
  custom-4448:
    title: 'Custom HTML'
    attributes:
      html: '<div class="loader"></div>'
  owlcarousel-4121:
    title: 'Owl Carousel'
    attributes:
      class: ''
      dots: enable
      autoplay: enable
      autoplaySpeed: ''
      imageOverlay: enable
      items:
        -
          image: 'gantry-media://header/pexels-photo-235509.jpeg'
          title: 'Shop Apparel'
          desc: 'Credibly deliver next-generation collaboration and idea-sharing with B2C materials. Conveniently reintermediate innovative.'
          link: shop
          linktext: 'Shop Now'
          buttonclass: 'button-primary large'
          name: Shop
        -
          image: 'gantry-media://header/pexels-photo-737471.jpeg'
          title: Podcasts
          desc: 'Credibly deliver next-generation collaboration and idea-sharing with B2C materials. Conveniently reintermediate innovative.'
          link: podcasts
          linktext: 'Listen Now'
          buttonclass: large
          name: Podcast
        -
          image: 'gantry-media://header/pexels-photo-247298.jpeg'
          title: 'RC of the Month'
          desc: 'Energistically network fully tested materials rather than 2.0 markets. Phosfluorescently synthesize high.'
          link: rc-of-the-month
          linktext: 'Read Now'
          buttonclass: large
          name: 'RC of the Month'
        -
          image: 'gantry-media://header/pexels-photo-242829.jpeg'
          title: Initiatives
          desc: 'Energistically network fully tested materials rather than 2.0 markets. Phosfluorescently synthesize high.'
          link: initiatives
          linktext: 'View All'
          buttonclass: large
          name: Intiatives
    block:
      fixed: '1'
  custom-6676:
    title: 'Custom HTML'
    attributes:
      html: '[grid_plus name="home_grid_blog"]'
      filter: '1'
    block:
      class: feature-post
  custom-4035:
    title: 'Custom HTML'
    attributes:
      html: '[grid_plus name="podcast_grid_test"]'
      filter: '1'
  custom-9319:
    title: 'Custom HTML'
    attributes:
      html: "[grid_plus name=\"home_grid_social\"]\n"
      filter: '1'
    block:
      class: home-social
