version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1513089165
layout:
  navigation: {  }
  /header/:
    -
      - owlcarousel-4206
  /intro/: {  }
  /features/: {  }
  /utility/: {  }
  /above/: {  }
  /testimonials/: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'mainbar 75':
          -
            - contentcubes-7157
      -
        'sidebar 25': {  }
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  header:
    attributes:
      boxed: '2'
      class: ''
  intro:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  owlcarousel-4206:
    title: 'Owl Carousel'
    attributes:
      dots: enable
      autoplay: enable
      autoplaySpeed: ''
      imageOverlay: enable
      items:
        -
          image: 'gantry-media://header/pexels-photo-235509.jpeg'
          title: 'Shop Women'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at rutrum orci, vitae gravida purus. Duis id enim nunc. Pellentesque justo quam, posuere eu sagittis quis, varius nec risus. Mauris ante lacus, fermentum ac urna nec, bibendum ornare lorem. Mauris a metus dictum lacus accumsan imperdiet non cursus velit. '
          link: shop
          linktext: 'Shop Now'
          buttonclass: button-outline
          name: 'Shop Women'
        -
          image: 'gantry-media://header/pexels-photo-247298.jpeg'
          title: Podcasts
          desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at rutrum orci, vitae gravida purus. Duis id enim nunc. Pellentesque justo quam, posuere eu sagittis quis, varius nec risus. Mauris ante lacus, fermentum ac urna nec, bibendum ornare lorem. Mauris a metus dictum lacus accumsan imperdiet non cursus velit. '
          link: podcasts
          linktext: 'Listen Now'
          buttonclass: button-outline
          name: Podcasts
  contentcubes-7157:
    title: 'Content Cubes'
    attributes:
      title: ''
      items:
        -
          image: 'gantry-media://2017/12/pexels-photo-227288.jpeg'
          imageposition: left
          label: Shop
          title: 'The New Fall Collection is Here'
          link: shop
          linktext: 'Shop New Arrivals'
          desc: 'Nulla quis lorem ut libero malesuada feugiat. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Nulla porttitor accumsan tincidunt. Donec sollicitudin molestie malesuada. '
          buttonclass: button-outline
          buttontarget: _self
          name: 'New Arrivals'
        -
          image: 'gantry-media://2017/12/pexels-photo-196666-768x512.jpeg'
          imageposition: left
          label: 'About Us'
          title: 'Experience the RC Brand'
          link: about
          linktext: 'Who We Are'
          desc: ''
          buttonclass: button-outline
          buttontarget: _self
          name: 'The Brand'
        -
          image: 'gantry-media://2017/12/pexels-photo-196666-768x512.jpeg'
          imageposition: left
          label: Initiatives
          title: 'RC E-Mentoring'
          link: initiatives
          linktext: 'View All'
          desc: ''
          buttonclass: button-outline
          buttontarget: _self
          name: Initiative
        -
          image: 'gantry-media://2017/12/pexels-photo-607894-1024x793.jpeg'
          imageposition: left
          label: Blog
          title: 'RC of the Month'
          link: blog
          linktext: 'Read Now'
          desc: 'Cras ultricies ligula sed magna dictum porta. Donec rutrum congue leo eget malesuada. Sed porttitor lectus nibh. Sed porttitor lectus nibh. Pellentesque in ipsum id orci porta dapibus. Curabitur aliquet quam id dui posuere blandit. Vivamus suscipit tortor eget felis porttitor volutpat. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui.'
          buttonclass: button-outline
          buttontarget: _self
          name: Blog
        -
          image: ''
          video: 'gantry-media://2017/12/343647377.mp4'
          imageposition: left
          label: ''
          title: 'Visit the Beach'
          tags: {  }
          link: ''
          linktext: ''
          desc: ''
          buttonclass: ''
          buttontarget: _self
          name: 'Blog Video'
        -
          name: Facebook
        -
          name: Twitter
        -
          name: Subscribe
