preset: preset6
link:
  hover: '#ffffff'
navigation:
  background: 'rgba(71, 71, 71, 0)'
header:
  background: '#474747'
  text-color: '#ffffff'
footer:
  background: '#2a2a2a'
  text-color: '#ffffff'
