name: blog
timestamp: 1516703984
version: 7
preset:
  image: 'gantry-media://images/admin/layouts/2-col-right.png'
  name: 2-col-right
  timestamp: 1513307866
positions: {  }
sections:
  navigation: Navigation
  header: Header
  main: Main
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-3064: 'System Messages'
  logo:
    logo-7607: 'Logo / Image'
    logo-4355: 'Logo / Image'
  menu:
    menu-1609: Menu
    menu-5480: Menu
    menu-8406: Menu
    menu-1533: Menu
    menu-5220: Menu
  custom:
    custom-6564: 'Custom HTML'
    custom-4257: Breadcrumbs
    custom-5667: 'Custom HTML'
  contentarray:
    contentarray-5790: 'WordPress Posts'
  mobile-menu:
    mobile-menu-1349: Mobile-menu
  copyright:
    copyright-1747: Copyright
  spacer:
    spacer-3794: Spacer
  social:
    social-7655: Social
inherit:
  about:
    custom-4257: custom-3566
  default:
    footer: footer
    menu-5480: menu-1837
    menu-8406: menu-6570
    menu-1533: menu-9412
    menu-5220: menu-3453
    logo-4355: logo-9571
    copyright-1747: copyright-1736
    spacer-3794: spacer-2556
    social-7655: social-7256
