name: blog
timestamp: 1513403261
version: 7
preset:
  image: 'gantry-media://images/admin/layouts/2-col-right.png'
  name: 2-col-right
  timestamp: 1513307866
positions: {  }
sections:
  navigation: Navigation
  header: Header
  main: Main
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  content:
    system-content-1010: 'Page Content'
  copyright:
    copyright-1537: Copyright
  spacer:
    spacer-3170: Spacer
  branding:
    branding-9538: Branding
  mobile-menu:
    mobile-menu-1349: Mobile-menu
  messages:
    system-messages-2648: 'System Messages'
  logo:
    logo-4799: 'Logo / Image'
  menu:
    menu-6098: Menu
  owlcarousel:
    owlcarousel-6866: 'Owl Carousel'
inherit:
  default:
    navigation: navigation
    header: header
    system-messages-2648: system-messages-7972
    logo-4799: logo-9608
    menu-6098: menu-6409
    owlcarousel-6866: owlcarousel-7144
