name: blog
timestamp: 1513429078
version: 7
preset:
  image: 'gantry-media://images/admin/layouts/2-col-right.png'
  name: 2-col-right
  timestamp: 1513307866
positions: {  }
sections:
  navigation: Navigation
  header: Header
  main: Main
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-4799: 'Logo / Image'
  menu:
    menu-6098: Menu
  messages:
    system-messages-3860: 'System Messages'
  contentarray:
    contentarray-4262: 'WordPress Posts'
    contentarray-5790: 'WordPress Posts'
  copyright:
    copyright-1537: Copyright
  spacer:
    spacer-3170: Spacer
  branding:
    branding-9538: Branding
  mobile-menu:
    mobile-menu-1349: Mobile-menu
inherit:
  default:
    logo-4799: logo-9608
    menu-6098: menu-6409
    system-messages-3860: system-messages-7972
