version: 2
preset:
  image: 'gantry-media://images/admin/layouts/2-col-right.png'
  name: 2-col-right
  timestamp: 1513307866
layout:
  /navigation/:
    -
      - system-messages-3064
    -
      - 'logo-7607 25'
      - 'menu-1609 50'
      - 'menu-8000 25'
    -
      - custom-6564
  /header/: {  }
  /container-main/:
    -
      -
        'main 80':
          -
            - custom-4257
          -
            - custom-5667
      -
        'sidebar 20':
          -
            - contentarray-5790
  footer: {  }
  offcanvas:
    -
      - mobile-menu-1349
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
  header:
    attributes:
      boxed: '2'
      class: ''
  main:
    attributes:
      class: ''
  sidebar:
    type: section
    subtype: aside
    block:
      fixed: 1
  container-main:
    attributes:
      boxed: ''
      class: blog-section
      extra: {  }
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  logo-7607:
    title: 'Logo / Image'
    attributes:
      image: 'gantry-media://2017/12/rc_logo.png'
      svg: ''
  menu-1609:
    attributes:
      menu: primary-menu
      base: /
      mobileTarget: '1'
    block:
      class: center
  menu-8000:
    attributes:
      menu: user-menu
      mobileTarget: '1'
    block:
      class: menu-right
  custom-6564:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"tagline\">\n   <div class=\"tag\">Blog</div>\n   <h1>The Experience</h1>\n</div>"
  custom-4257:
    title: Breadcrumbs
    inherit:
      outline: about
      particle: custom-3566
      include:
        - attributes
        - block
  custom-5667:
    title: 'Custom HTML'
    attributes:
      html: '[grid_plus name="blog_grid"]'
      filter: '1'
  contentarray-5790:
    title: 'WordPress Posts'
    attributes:
      enabled: 0
      post:
        filter:
          categories: '1 20'
          posts: ''
          sticky: ''
        limit:
          total: '10'
          columns: '1'
          start: '0'
        sort:
          orderby: date
          ordering: DESC
        display:
          image:
            enabled: ''
          title:
            enabled: show
          date:
            enabled: ''
          read_more:
            enabled: ''
          author:
            enabled: ''
          category:
            enabled: ''
          text:
            type: ''
