name: blog_single
timestamp: 1530089458
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
positions: {  }
sections:
  navigation: Navigation
  header: Header
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-3233: 'System Messages'
  logo:
    logo-4434: 'Logo / Image'
    logo-7399: 'Logo / Image'
  menu:
    menu-9378: Menu
    menu-7010: Menu
    menu-9151: Menu
    menu-8736: Menu
    menu-6832: Menu
    menu-5615: Menu
  custom:
    custom-4824: 'Custom HTML'
    custom-4017: Breadcrumbs
  content:
    system-content-5815: 'Page Content'
  mobile-menu:
    mobile-menu-9910: Mobile-menu
  copyright:
    copyright-5318: Copyright
  spacer:
    spacer-2067: Spacer
  social:
    social-1948: Social
inherit:
  about:
    system-messages-3233: system-messages-2770
    logo-4434: logo-5067
    menu-9378: menu-2524
    menu-7010: menu-5767
    custom-4017: custom-3566
  default:
    footer: footer
    menu-9151: menu-1837
    menu-8736: menu-6570
    menu-6832: menu-9412
    menu-5615: menu-3453
    logo-7399: logo-9571
    copyright-5318: copyright-1736
    spacer-2067: spacer-2556
    social-1948: social-7256
