preset: preset6
navigation:
  background-image: 'gantry-media://header/pexels-photo-1181317.jpeg'
header:
  background-image: 'gantry-media://2018/01/pexels-photo-170290-1024x683.jpeg'
  background-overlay: enabled
footer:
  background: '#2a2a2a'
