name: shop_-_description
timestamp: 1517578418
version: 7
preset:
  image: 'gantry-admin://images/layouts/2-col-right.png'
  name: 2-col-right
  timestamp: 1513307168
positions:
  header: Header
  aside: Aside
sections:
  header: Header
  navigation: Navigation
  messages: Messages
  main: Main
  footer: Footer
  aside: Aside
  offcanvas: Offcanvas
particles:
  position:
    position-header: Header
    position-aside: Aside
  menu:
    menu-8139: Menu
    menu-1144: Menu
  messages:
    system-messages-9548: 'System Messages'
  custom:
    custom-8900: Breadcrumbs
  content:
    system-content-6156: 'Page Content'
  copyright:
    copyright-4351: Copyright
  spacer:
    spacer-4575: Spacer
  branding:
    branding-8622: Branding
  mobile-menu:
    mobile-menu-1058: Mobile-menu
inherit:
  about:
    custom-8900: custom-3566
