version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: fullpage
  timestamp: 1513263333
layout:
  /navigation/:
    -
      - system-messages-2488
    -
      - 'logo-4923 25'
      - 'menu-5771 50'
      - 'menu-7970 25'
    -
      - custom-4044
  /header/: {  }
  /main/:
    -
      - custom-8900
    -
      - system-content-6156
  footer: {  }
  offcanvas:
    -
      - mobile-menu-1058
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
  header:
    attributes:
      boxed: ''
      class: ''
  main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
content:
  system-messages-2488:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: system-messages-2770
  logo-4923:
    title: 'Logo / Image'
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: logo-5067
  menu-5771:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-2524
  menu-7970:
    inherit:
      outline: about
      include:
        - attributes
        - block
      particle: menu-5767
  custom-4044:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"tagline\">\n <div class=\"tag\">Products</div>\n   <h1>Shop</h1>\n</div>"
  custom-8900:
    title: Breadcrumbs
    inherit:
      outline: about
      particle: custom-3566
      include:
        - attributes
        - block
