version: 2
preset:
  image: 'gantry-admin://images/layouts/2-col-right.png'
  name: 2-col-right
  timestamp: 1513307168
layout:
  /container-main/:
    -
      -
        'header 50':
          -
            - position-header
        navigation:
          -
            - menu-8139
        messages:
          -
            - system-messages-9548
        main:
          -
            - custom-8900
          -
            - system-content-6156
        footer:
          -
            - 'copyright-4351 40'
            - 'spacer-4575 30'
            - 'branding-8622 30'
      -
        'aside 50':
          -
            - position-aside
  offcanvas:
    -
      - mobile-menu-1058
structure:
  navigation:
    type: section
  messages:
    type: section
  aside:
    block:
      fixed: 1
  container-main:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  custom-8900:
    title: Breadcrumbs
    inherit:
      outline: about
      particle: custom-3566
      include:
        - attributes
        - block
  position-aside:
    attributes:
      key: aside
